SELECT*FROM employee;
--1)RETRIEVE EMPLOYEE WHOSE SALARY IS BETWEEN 40000 AND 60000-USE BETWEEN OPERATOR
/* FIRST WAY TO SHOW */
SELECT*FROM employee
WHERE salary >= 40000 AND salary <=60000;
/*SECOND OPETION*/
SELECT salary FROM employee
WHERE salary BETWEEN 40000 AND 60000;

--2)FIND EMPLOYEE WHOSE LASTNAME END WITH RK USING KIKE OPERATOR
/*NOTE=> AGAR TUMHE LAST ME CHECK KARNA HAI TO % STARTING ME LAGANA HOGA 
AGAR STARING ME CHECK KARNA HO % STARING ME LAGANA HOGA!*/

SELECT*FROM employee
WHERE last_name LIKE '%rk';

--3)RETRIEVE EMPLOYEE WHO BELONG TO EITHER THE FINANCE OR MARKETING DEPARTMENTS--USING IN OPERATOR !
SELECT first_name,last_name,department FROM employee
WHERE DEPARTMENT IN('Finance','Market');