CREATE TABLE employee(
emp_id INT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
department VARCHAR(20),
salary NUMERIC(10,2),
joining_date DATE,
age INT
);
SELECT *FROM employee;


/* 	DATA SHOW KARNE KE LIYE FOLLOWING STEPS FOLLOW KARNE HONGE.*/
--A METHOD LECTURE NO.12 ME HAI
--B METHOD--
--1.SABSE PAHLE JO TABLE ME HEADING DII HUE HAI USE SE RELATED TABLE CREATE KARNI HOGI.
--2.USKE BAAD DATABASE ME JAKAR SCHEMA ME JAKR TABLE ME JAKR JIS NAAME SE TABLE BANI HUE HAI US PER CLICK KARNA HOGA VIEW IMPORT/EXPORT
-- PER CLICK KARKE GENERAL ME JAKR FILE PATH SELECT KARO GENERAL PER JAKAR HEADER CLICK KARNA KARO DATA AA JAYEGA 

