SELECT*FROM employee;
/*WRITE A QUERY WHOSE AGE IS GREATER THAN 50000 AND AGE MUST BE GREATER THAN 35*/
SELECT*FROM employee
WHERE age>=45 AND salary>=50000;

-- OR 	OPERATOR

SELECT*FROM employee
WHERE age>60 OR salary>=50000;

-- NOT OPERATOR

SELECT*FROM employee
WHERE NOT department='IT';